name: Symfony

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  symfony-tests:
    runs-on: ubuntu-latest
    steps:
    #  To automatically get bug fixes and new Php versions for shivammathur/setup-php,
    # change this to (see https://github.com/shivammathur/setup-php#bookmark-versioning):
    # uses: shivammathur/setup-php@v2
    - uses: shivammathur/setup-php@2cb9b829437ee246e9b3cac53555a39208ca6d28
      with:
        php-version: '8.1'
    - uses: actions/checkout@v3
    - name: Copy .env.test.local
      run: php -r "file_exists('.env.test.local') || copy('.env.test', '.env.test.local');"
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
    - name: Install Dependencies
      run: composer install --no-ansi --no-interaction

    - name: Lint YAML files
      run: bin/console lint:yaml config --parse-tags

    - name: Lint TWIG files
      run: bin/console --env=test lint:twig

    - name: Lint Containers
      run: bin/console lint:container

    - name: Static Analysis
      run: vendor/bin/phpstan analyse --level 4 src tests

    - name: Create Database and fill with data
      run: |
        bin/console --env=test doctrine:database:create
        bin/console --env=test doctrine:schema:create
        bin/console --env=test doctrine:fixtures:load -n

    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: bin/phpunit
